server:
  port: 3030
spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: userModule
          uri: http://localhost:3001/
          predicates:
            - Path=/users/**
        - id: blogModule
          uri: http://localhost:3002/
          predicates:
            - Path=/blogs/**
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:3000/eureka
  registerWithEureka:
    - true
  fetchRegistry:
    - true
